baseURL = "https://maku77.github.io/"
enableRobotsTXT = true
# googleAnalytics = "UA-63069513-1"
googleAnalytics = "G-X5962TDYXS"
languageCode = "ja-jp"
pygmentsCodeFences = true
pygmentsUseClasses = true
relativeurls = true
theme = "maku77"
title = "天才まくまくノート"

[markup.goldmark.renderer]
  unsafe = true

[params]
  AmazonId = "maku04-22"

