baseURL = "https://maku77.github.io/"
relativeurls = true
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsUseClasses = true
languageCode = "ja-jp"
timeZone = "Asia/Tokyo"
title = "天才まくまくノート"
# googleAnalytics = "UA-63069513-1"
googleAnalytics = "G-X5962TDYXS"
theme = "maku77"

[markup.goldmark.renderer]
  unsafe = true

[params]
  image = "img/site-logo.png"
  facebookAppId = "447708168769292"
  description = "天才星人まくのメモ"
  Author = "まく"
  AmazonId = "maku04-22"
  CustomSearchId = "partner-pub-6317852277883092:5930376365"

[module]
[[module.imports]]
  path = "github.com/maku77/hugo-module-maku-common"
